[{"oaci":"LFMH","iata":"EBU","name":"ST ETIENNE LOIRE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":45.53,"long":4.3,"nb_destinations":3},
{"oaci":"LFLL","iata":"LYS","name":"LYON ST EXUPERY","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":45.73,"long":5.08,"nb_destinations":116},
{"oaci":"LFLP","iata":"NCY","name":"ANNECY MEYTHET","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":45.93,"long":6.11,"nb_destinations":0},
{"oaci":"LFLS","iata":"GNB","name":"GRENOBLE ISERE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":45.36,"long":5.33,"nb_destinations":20},
{"oaci":"LFKJ","iata":"AJA","name":"AJACCIO NAPOLEON BONAPARTE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":41.92,"long":8.8,"nb_destinations":24},
{"oaci":"LFLC","iata":"CFE","name":"CLERMONT FERRAND AUVERGNE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":45.79,"long":3.16,"nb_destinations":7},
{"oaci":"LFSD","iata":"DIJ","name":"DIJON LONGVIC","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":47.27,"long":5.09,"nb_destinations":0},
{"oaci":"LFKF","iata":"FSC","name":"FIGARI SUD CORSE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":41.5,"long":9.1,"nb_destinations":18},
{"oaci":"LFLB","iata":"CMF","name":"CHAMBERY AIX LES BAINS","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":45.64,"long":5.88,"nb_destinations":18},
{"oaci":"LFMN","iata":"NCE","name":"NICE COTE D'AZUR","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.67,"long":7.22,"nb_destinations":103},
{"oaci":"LFBX","iata":"PGX","name":"PERIGUEUX BASSILLAC","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":45.2,"long":0.82,"nb_destinations":0},
{"oaci":"LFOH","iata":"LEH","name":"LE HAVRE OCTEVILLE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":49.53,"long":0.09,"nb_destinations":0},
{"oaci":"LFCR","iata":"RDZ","name":"RODEZ AVEYRON","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":44.41,"long":2.48,"nb_destinations":3},
{"oaci":"LFCI","iata":"LBI","name":"ALBI LE SEQUESTRE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.91,"long":2.12,"nb_destinations":0},
{"oaci":"LFRB","iata":"BES","name":"BREST BRETAGNE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":48.45,"long":-4.42,"nb_destinations":23},
{"oaci":"LFQQ","iata":"LIL","name":"LILLE LESQUIN","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":50.56,"long":3.09,"nb_destinations":55},
{"oaci":"LFKB","iata":"BIA","name":"BASTIA PORETTA","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":42.55,"long":9.48,"nb_destinations":33},
{"oaci":"LFKC","iata":"CLY","name":"CALVI STE CATHERINE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":42.52,"long":8.79,"nb_destinations":18},
{"oaci":"LFBV","iata":"BVE_","name":"BRIVE LA ROCHE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":45.15,"long":1.47,"nb_destinations":0},
{"oaci":"LFEY","iata":"IDY","name":"ILE D'YEU","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":46.72,"long":-2.39,"nb_destinations":0},
{"oaci":"LFBU","iata":"ANG","name":"ANGOULEME BRIE CHAMPNIERS","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":45.73,"long":0.22,"nb_destinations":0},
{"oaci":"LFBZ","iata":"BIQ","name":"BIARRITZ PAYS BASQUE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.47,"long":-1.53,"nb_destinations":19},
{"oaci":"LFML","iata":"MRS","name":"MARSEILLE PROVENCE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.44,"long":5.22,"nb_destinations":95},
{"oaci":"LFMI","iata":"QIE","name":"ISTRES LE TUBE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.52,"long":4.92,"nb_destinations":0},
{"oaci":"LFSR","iata":"RHE","name":"REIMS CHAMPAGNE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":49.31,"long":4.05,"nb_destinations":0},
{"oaci":"LFOK","iata":"XCR","name":"CHALONS VATRY","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":48.77,"long":4.21,"nb_destinations":9},
{"oaci":"LFMS","iata":"XAS","name":"ALES CEVENNES","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":44.07,"long":4.14,"nb_destinations":0},
{"oaci":"LFGJ","iata":"DLE","name":"DOLE TAVAUX","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":47.04,"long":5.44,"nb_destinations":3},
{"oaci":"LFLJ","iata":"CVF","name":"COURCHEVEL","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":45.4,"long":6.63,"nb_destinations":0},
{"oaci":"LFSL","iata":"BVE","name":"BRIVE SOUILLAC","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":45.04,"long":1.49,"nb_destinations":2},
{"oaci":"LFRZ","iata":"SNR","name":"ST NAZAIRE MONTOIR","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":47.31,"long":-2.16,"nb_destinations":1},
{"oaci":"LFHP","iata":"LPY","name":"LE PUY LOUDES","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":45.08,"long":3.76,"nb_destinations":0},
{"oaci":"LFOP","iata":"URO","name":"ROUEN VALLEE DE SEINE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":49.39,"long":1.18,"nb_destinations":0},
{"oaci":"LFTG","iata":"JCA","name":"CANNES","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.54,"long":7.04,"nb_destinations":0},
{"oaci":"LFRM","iata":"LME","name":"LE MANS ARNAGE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":47.95,"long":0.2,"nb_destinations":0},
{"oaci":"LFLH","iata":"XCD","name":"CHALON CHAMPFORGEUIL","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":46.83,"long":4.82,"nb_destinations":0},
{"oaci":"LFGA","iata":"CMR","name":"COLMAR HOUSSEN","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":48.11,"long":7.36,"nb_destinations":0},
{"oaci":"LFJA","iata":"XCW","name":"CHAUMONT SEMOUTIER","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":48.09,"long":5.05,"nb_destinations":0},
{"oaci":"LFMK","iata":"CCF","name":"CARCASSONNE SALVAZA","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.22,"long":2.31,"nb_destinations":10},
{"oaci":"LFTZ","iata":"LTT","name":"ST TROPEZ LA MOLE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.21,"long":6.48,"nb_destinations":0},
{"oaci":"LFDN","iata":"RCO","name":"ROCHEFORT CHARENTE MARITIME","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":45.89,"long":-0.98,"nb_destinations":0},
{"oaci":"LFJL","iata":"ETZ","name":"METZ NANCY LORRAINE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":48.98,"long":6.25,"nb_destinations":14},
{"oaci":"LFOB","iata":"BVA","name":"BEAUVAIS TILLE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":49.45,"long":2.11,"nb_destinations":59},
{"oaci":"LFRS","iata":"NTE","name":"NANTES ATLANTIQUE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":47.16,"long":-1.61,"nb_destinations":86},
{"oaci":"LFLX","iata":"CHR","name":"CHATEAUROUX DEOLS","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":46.86,"long":1.72,"nb_destinations":0},
{"oaci":"LFBE","iata":"EGC","name":"BERGERAC ROUMANIERE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":44.82,"long":0.52,"nb_destinations":12},
{"oaci":"LFBD","iata":"BOD","name":"BORDEAUX MERIGNAC","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":44.83,"long":-0.72,"nb_destinations":75},
{"oaci":"LFPT","iata":"POX","name":"PONTOISE CORMEILLES EN VEXIN","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":49.1,"long":2.04,"nb_destinations":0},
{"oaci":"LFRG","iata":"DOL","name":"DEAUVILLE NORMANDIE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":49.36,"long":0.16,"nb_destinations":11},
{"oaci":"LFAT","iata":"LTQ","name":"LE TOUQUET COTE D’OPALE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":50.51,"long":1.63,"nb_destinations":0},
{"oaci":"LFSG","iata":"EPL","name":"EPINAL MIRECOURT","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":48.33,"long":6.07,"nb_destinations":0},
{"oaci":"LFLU","iata":"VAF","name":"VALENCE CHABEUIL","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":44.92,"long":4.97,"nb_destinations":0},
{"oaci":"LFBA","iata":"AGF","name":"AGEN LA GARENNE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":44.17,"long":0.59,"nb_destinations":1},
{"oaci":"LFLO","iata":"RNE","name":"ROANNE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":46.05,"long":4,"nb_destinations":0},
{"oaci":"LFRC","iata":"CER","name":"CHERBOURG MAUPERTUS","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":49.65,"long":-1.48,"nb_destinations":0},
{"oaci":"LFCK","iata":"DCM","name":"CASTRES MAZAMET","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.56,"long":2.29,"nb_destinations":1},
{"oaci":"LFRT","iata":"SBK","name":"ST BRIEUC ARMOR","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":48.54,"long":-2.86,"nb_destinations":0},
{"oaci":"LFBP","iata":"PUF","name":"PAU PYRENEES","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.38,"long":-0.42,"nb_destinations":6},
{"oaci":"LFRQ","iata":"UIP","name":"QUIMPER PLUGUFFAN","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":47.98,"long":-4.17,"nb_destinations":2},
{"oaci":"LFBO","iata":"TLS","name":"TOULOUSE BLAGNAC","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.64,"long":1.37,"nb_destinations":80},
{"oaci":"LFBH","iata":"LRH","name":"LA ROCHELLE ILE DE RE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":46.18,"long":-1.2,"nb_destinations":12},
{"oaci":"LFKO","iata":"PRP","name":"PROPRIANO","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":41.66,"long":8.89,"nb_destinations":0},
{"oaci":"LFBI","iata":"PIS","name":"POITIERS BIARD","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":46.59,"long":0.31,"nb_destinations":4},
{"oaci":"LFBL","iata":"LIG","name":"LIMOGES BELLEGARDE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":45.86,"long":1.18,"nb_destinations":9},
{"oaci":"LFMP","iata":"PGF","name":"PERPIGNAN RIVESALTES","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":42.74,"long":2.87,"nb_destinations":7},
{"oaci":"LFOT","iata":"TUF","name":"TOURS VAL DE LOIRE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":47.43,"long":0.72,"nb_destinations":5},
{"oaci":"LFMT","iata":"MPL","name":"MONTPELLIER MEDITERRANEE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.58,"long":3.96,"nb_destinations":25},
{"oaci":"LFMU","iata":"BZR","name":"BEZIERS VIAS","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.32,"long":3.35,"nb_destinations":8},
{"oaci":"LFBT","iata":"LDE","name":"TARBES LOURDES PYRENEES","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.19,"long":0.01,"nb_destinations":22},
{"oaci":"LFRO","iata":"LAI","name":"LANNION","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":48.75,"long":-3.47,"nb_destinations":1},
{"oaci":"LFRN","iata":"RNS","name":"RENNES ST JACQUES","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":48.07,"long":-1.73,"nb_destinations":20},
{"oaci":"LFRD","iata":"DNR","name":"DINARD PLEURTUIT ST MALO","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":48.59,"long":-2.08,"nb_destinations":2},
{"oaci":"LFJR","iata":"ANE","name":"ANGERS MARCE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":47.56,"long":-0.31,"nb_destinations":1},
{"oaci":"LFRH","iata":"LRT","name":"LORIENT LANN BIHOUE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":47.76,"long":-3.44,"nb_destinations":2},
{"oaci":"LFRK","iata":"CFR","name":"CAEN CARPIQUET","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":49.17,"long":-0.45,"nb_destinations":4},
{"oaci":"LFMV","iata":"AVN","name":"AVIGNON CAUMONT","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.91,"long":4.9,"nb_destinations":3},
{"oaci":"LFPB","iata":"LBG","name":"PARIS LE BOURGET","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":48.97,"long":2.44,"nb_destinations":0},
{"oaci":"LFST","iata":"SXB","name":"STRASBOURG ENTZHEIM","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":48.54,"long":7.63,"nb_destinations":30},
{"oaci":"LFSN","iata":"ENC","name":"NANCY ESSEY","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":48.69,"long":6.23,"nb_destinations":0},
{"oaci":"LFSF","iata":"MZM","name":"METZ FRESCATY","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":49.08,"long":6.13,"nb_destinations":0},
{"oaci":"LFLV","iata":"VHY","name":"VICHY CHARMEIL","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":46.17,"long":3.4,"nb_destinations":0},
{"oaci":"LFTH","iata":"TLN","name":"TOULON HYERES","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.1,"long":6.15,"nb_destinations":8},
{"oaci":"LFSB","iata":"MLH","name":"BALE MULHOUSE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":47.59,"long":7.53,"nb_destinations":94},
{"oaci":"LFTW","iata":"FNI","name":"NIMES GARONS","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":43.76,"long":4.42,"nb_destinations":4},
{"oaci":"LFLW","iata":"AUR","name":"AURILLAC","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":44.9,"long":2.42,"nb_destinations":1},
{"oaci":"LFPG","iata":"CDG","name":"PARIS CHARLES DE GAULLE","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":49.01,"long":2.55,"nb_destinations":295},
{"oaci":"LFPO","iata":"ORY","name":"PARIS ORLY","country":"FR","country_name":"France (Métrop.)","zone":"M","haul":"CC","lat":48.72,"long":2.38,"nb_destinations":155}]
